export {default as Home} from './Home/Home'
export {default as Characters} from './CharactersPage/Characters'
export {default as HeroPage} from './HeroPage/HeroPage'
export {default as SearchPage} from './SearchPage/SearchPage'
export {default as FavoritesPage} from './FavoritesPage/FavoritesPage'